### ISSUE TITLE
[FEATURE] User Profile Page

### ISSUE THREAD

**Issue by saenyakorn** [thinc-org/cugetreg-frontend#307]
**Is your feature request related to a problem? Please describe.**
เนื่องจากตอนนี้ User บางคนอาจจะจำไม่ได้ว่าตัวเองลงวิชาเลือกไปกี่หน่วยกิตแล้ว

**Describe the solution you'd like**
สร้างหน้า Profile ขึ้นมา คล้าย ๆ กับของ ศูนย์การศึกษาทั่วไป เพื่อดูรายละเอียดเรื่อง จำนวนหน่วยกิต และอื่น ๆ 

**Describe alternatives you've considered**

**Additional context**

**Comment by bombnp** [comment]
This is very similar to my idea of course portfolio, where it shows total course credit for all course types (required, elective, etc.), which are designated by the user themselves (so we don't have to code to match all curriculum)

**Comment by bombnp** [comment]
Moved to #372
