### ISSUE TITLE
[FEATURE] Add mandatory course management system 

### ISSUE THREAD

**Issue by saenyakorn** [thinc-org/cugetreg-frontend#308]
**Is your feature request related to a problem? Please describe.**
ตอนนี้เรายังไม่มีข้อมูลวิชาบังคับจากทุกคณะ และการจะเติมให้ครบด้วยตัวทีมงานเองเป็นไปได้ยาก 

**Describe the solution you'd like**
เพ่มระบบจัดการวิชาบังคับ แล้วขอความร่วมมือให้แต่ละสโมสร ช่วยกันบริหารจัดการ และประชาสัมพันธ์เว็บไซต์ CU Get Reg

**Describe alternatives you've considered**

**Additional context**

**Comment by bombnp** [comment]
Closed for no info
