### ISSUE TITLE
[BUG] Recommendation text visible when there are no recommendation

### ISSUE THREAD

**Issue by new5558** [thinc-org/cugetreg-frontend#311]
**Describe the bug**
See recommendation text when there are no recommendations. "คุณอาจสนใจวิชาเหล่านี้"

**To Reproduce**
1. Activate google optimize [random varaint](https://www.googleoptimize.com/opt_set_cookie?uiv2&id=OPT-P9XQVG8&gtm_auth=eGB0WZl6th2-1s0WzM0uQg&gtm_debug&gtm_experiment=OPT-P9XQVG8_OPT-54XQL%241&gtm_preview=opt_preview-slim&redirect=https%3A%2F%2Fwww.google-analytics.com%2Fgtm%2Fset_cookie%3Fuiv2%26id%3DOPT-P9XQVG8%26gtm_auth%3DeGB0WZl6th2-1s0WzM0uQg%26gtm_debug%26gtm_experiment%3DOPT-P9XQVG8_OPT-54XQL%25241%26gtm_preview%3Dopt_preview-slim%26redirect%3Dhttps%253A%252F%252Foptimize.google.com%252Foptimize%252Fsharepreview%253Fid%253DOPT-P9XQVG8%2526gtm_experiment%253DOPT-P9XQVG8_OPT-54XQL%2525241%2526url%253Dhttps%25253A%25252F%25252Fcugetreg.com%25252FS%25252Fcourses%2526opt_experiment_name%253DRecommendation%252520Text%2526opt_variation_name%253DRANDOM%2526slim%253Dtrue%2526container_name%253DCU%252520Get%252520Reg%26optimize_editor&optimize_editor) (Also has a problem on Cosine variant) and go to course page 
2. Add some courses
3. Refresh page

**Expected behavior**
No course recommendation

**Screenshots**
![image](https://user-images.githubusercontent.com/12471844/148646979-ea7e8097-8d50-4c22-99c1-60a63e3b4c36.png)

**Desktop (please complete the following information):**
 All browsers and operating systems but easiest to reproduce on Safari MacOS

**Smartphone (please complete the following information):**
All browsers and operating systems

**Additional context**
-

**Comment by saengowp** [comment]
Also, Possible race condition in Recommendation Text due to the recommendation being retrieved before Course Cart is loaded.
